In [1]:
import pandas as pd

df = pd.read_csv('borg_traces_data.csv')

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 405894 entries, 0 to 405893
Data columns (total 34 columns):
 #   Column                           Non-Null Count   Dtype
---  ------                           --------------   -----
 0   Unnamed: 0                       405894 non-null  int64
 1   time                             405894 non-null  int64
 2   instance_events_type             405894 non-null  int64
 3   collection_id                    405894 non-null  int64
 4   scheduling_class                 405894 non-null  int64
 5   collection_type                  405894 non-null  int64
 6   priority                         405894 non-null  int64
 7   alloc_collection_id              405894 non-null  int64
 8   instance_index                   405894 non-null  int64
 9   machine_id                       405894 non-null  int64
 10  resource_request                 405120 non-null  object
 11  constraint                       405894 non-null  object
 12  collections_events_type          405894 non-null  int64
 13  user                             405894 non-null  object
 14  collection_name                  405894 non-null  object
 15  collection_logical_name          405894 non-null  object
 16  start_after_collection_ids       405894 non-null  object
 17  vertical_scaling                 404935 non-null  float64
 18  scheduler                        404935 non-null  float64
 19  start_time                       405894 non-null  int64
 20  end_time                         405894 non-null  int64
 21  average_usage                    405894 non-null  object
 22  maximum_usage                    405894 non-null  object
 23  random_sample_usage              405894 non-null  object
 24  assigned_memory                  405894 non-null  float64
 25  page_cache_memory                405894 non-null  float64
 26  cycles_per_instruction           281206 non-null  float64
 27  memory_accesses_per_instruction  281206 non-null  float64
 28  sample_rate                      405894 non-null  float64
 29  cpu_usage_distribution           405894 non-null  object
 30  tail_cpu_usage_distribution      405894 non-null  object
 31  cluster                          405894 non-null  int64
 32  event                            405894 non-null  object
 33  failed                           405894 non-null  int64
dtypes: float64(7), int64(15), object(12)
memory usage: 105.3+ MB

In [2]:
df.head()

,Unnamed: 0,time,instance_events_type,collection_id,scheduling_class,collection_type,priority,alloc_collection_id,instance_index,machine_id,...,assigned_memory,page_cache_memory,cycles_per_instruction,memory_accesses_per_instruction,sample_rate,cpu_usage_distribution,tail_cpu_usage_distribution,cluster,event,failed
0,0,0,2,94591244395,3,1,200,0,144,168846390496,...,0.014435,0.000415,NaN,NaN,1.0,[0.00314331 0.00381088 0.00401306 0.00415039 0...,[0.00535583 0.00541687 0.00548553 0.00554657 0...,7,FAIL,1
1,1,2517305308183,2,260697606809,2,0,360,221495397286,335,85515092,...,0.000000,0.000000,NaN,NaN,1.0,[1.23977661e-05 1.23977661e-05 1.23977661e-05 ...,[1.23977661e-05 1.23977661e-05 1.23977661e-05 ...,7,FAIL,1
2,2,195684022913,6,276227177776,2,0,103,0,376,169321752432,...,0.010422,0.000235,0.939919,0.001318,1.0,[0.01344299 0.01809692 0.0201416 0.02246094 0...,[0.02902222 0.02929688 0.0295105 0.0296936 0...,7,SCHEDULE,0
3,3,0,2,10507389885,3,0,200,0,1977,178294817221,...,0.041626,0.000225,1.359102,0.007643,1.0,[0.03704834 0.04125977 0.04290771 0.04425049 0...,[0.05535889 0.05584717 0.05633545 0.05718994 0...,8,FAIL,1
4,4,1810627494172,3,25911621841,2,0,0,0,3907,231364893292,...,0.000272,0.000010,NaN,NaN,1.0,[0. 0. 0. 0. 0...,[0.00041485 0.00041485 0.00041485 0.00041485 0...,2,FINISH,0

In [3]:
null_labels = {}
for label,i in enumerate(df.isnull().sum()):
    if i !=0:
        null_labels[label] = i

print(null_labels)

{10: 774, 17: 959, 18: 959, 26: 124688, 27: 124688}

In [4]:
labels = [df.columns[26],df.columns[27]]

In [5]:
df.drop(labels,axis=1,inplace=True)
df = df.dropna()

In [6]:
resources = (df[df.columns[10]].dropna())

In [7]:
import ast
cpus = []
memorys = []
lst = []

for resouce in resources:
    resouce = ast.literal_eval(resouce)
    cpus.append(resouce['cpus'])
    memorys.append(resouce['memory'])

In [8]:
df = df.dropna()
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 404161 entries, 0 to 405893
Data columns (total 32 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   Unnamed: 0                   404161 non-null  int64
 1   time                         404161 non-null  int64
 2   instance_events_type         404161 non-null  int64
 3   collection_id                404161 non-null  int64
 4   scheduling_class             404161 non-null  int64
 5   collection_type              404161 non-null  int64
 6   priority                     404161 non-null  int64
 7   alloc_collection_id          404161 non-null  int64
 8   instance_index               404161 non-null  int64
 9   machine_id                   404161 non-null  int64
 10  resource_request             404161 non-null  object
 11  constraint                   404161 non-null  object
 12  collections_events_type      404161 non-null  int64
 13  user                         404161 non-null  object
 14  collection_name              404161 non-null  object
 15  collection_logical_name      404161 non-null  object
 16  start_after_collection_ids   404161 non-null  object
 17  vertical_scaling             404161 non-null  float64
 18  scheduler                    404161 non-null  float64
 19  start_time                   404161 non-null  int64
 20  end_time                     404161 non-null  int64
 21  average_usage                404161 non-null  object
 22  maximum_usage                404161 non-null  object
 23  random_sample_usage          404161 non-null  object
 24  assigned_memory              404161 non-null  float64
 25  page_cache_memory            404161 non-null  float64
 26  sample_rate                  404161 non-null  float64
 27  cpu_usage_distribution       404161 non-null  object
 28  tail_cpu_usage_distribution  404161 non-null  object
 29  cluster                      404161 non-null  int64
 30  event                        404161 non-null  object
 31  failed                       404161 non-null  int64
dtypes: float64(5), int64(15), object(12)
memory usage: 101.8+ MB

In [9]:
df.drop(df.columns[10],inplace=True,axis=1)
df['cpus'] = cpus
df['memory'] = memorys

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 404161 entries, 0 to 405893
Data columns (total 33 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   Unnamed: 0                   404161 non-null  int64
 1   time                         404161 non-null  int64
 2   instance_events_type         404161 non-null  int64
 3   collection_id                404161 non-null  int64
 4   scheduling_class             404161 non-null  int64
 5   collection_type              404161 non-null  int64
 6   priority                     404161 non-null  int64
 7   alloc_collection_id          404161 non-null  int64
 8   instance_index               404161 non-null  int64
 9   machine_id                   404161 non-null  int64
 10  constraint                   404161 non-null  object
 11  collections_events_type      404161 non-null  int64
 12  user                         404161 non-null  object
 13  collection_name              404161 non-null  object
 14  collection_logical_name      404161 non-null  object
 15  start_after_collection_ids   404161 non-null  object
 16  vertical_scaling             404161 non-null  float64
 17  scheduler                    404161 non-null  float64
 18  start_time                   404161 non-null  int64
 19  end_time                     404161 non-null  int64
 20  average_usage                404161 non-null  object
 21  maximum_usage                404161 non-null  object
 22  random_sample_usage          404161 non-null  object
 23  assigned_memory              404161 non-null  float64
 24  page_cache_memory            404161 non-null  float64
 25  sample_rate                  404161 non-null  float64
 26  cpu_usage_distribution       404161 non-null  object
 27  tail_cpu_usage_distribution  404161 non-null  object
 28  cluster                      404161 non-null  int64
 29  event                        404161 non-null  object
 30  failed                       404161 non-null  int64
 31  cpus                         404161 non-null  float64
 32  memory                       404161 non-null  float64
dtypes: float64(7), int64(15), object(11)
memory usage: 104.8+ MB

In [11]:
df.head()

,Unnamed: 0,time,instance_events_type,collection_id,scheduling_class,collection_type,priority,alloc_collection_id,instance_index,machine_id,...,assigned_memory,page_cache_memory,sample_rate,cpu_usage_distribution,tail_cpu_usage_distribution,cluster,event,failed,cpus,memory
0,0,0,2,94591244395,3,1,200,0,144,168846390496,...,0.014435,0.000415,1.0,[0.00314331 0.00381088 0.00401306 0.00415039 0...,[0.00535583 0.00541687 0.00548553 0.00554657 0...,7,FAIL,1,0.020660,0.014435
1,1,2517305308183,2,260697606809,2,0,360,221495397286,335,85515092,...,0.000000,0.000000,1.0,[1.23977661e-05 1.23977661e-05 1.23977661e-05 ...,[1.23977661e-05 1.23977661e-05 1.23977661e-05 ...,7,FAIL,1,0.007240,0.001303
2,2,195684022913,6,276227177776,2,0,103,0,376,169321752432,...,0.010422,0.000235,1.0,[0.01344299 0.01809692 0.0201416 0.02246094 0...,[0.02902222 0.02929688 0.0295105 0.0296936 0...,7,SCHEDULE,0,0.048584,0.004166
3,3,0,2,10507389885,3,0,200,0,1977,178294817221,...,0.041626,0.000225,1.0,[0.03704834 0.04125977 0.04290771 0.04425049 0...,[0.05535889 0.05584717 0.05633545 0.05718994 0...,8,FAIL,1,0.070435,0.041626
4,4,1810627494172,3,25911621841,2,0,0,0,3907,231364893292,...,0.000272,0.000010,1.0,[0. 0. 0. 0. 0...,[0.00041485 0.00041485 0.00041485 0.00041485 0...,2,FINISH,0,0.002449,0.000232

In [12]:
cpu_dist = df['cpu_usage_distribution']
cpu_tail = df['tail_cpu_usage_distribution']

In [13]:
df = pd.DataFrame(df)

In [14]:
df.head()

,Unnamed: 0,time,instance_events_type,collection_id,scheduling_class,collection_type,priority,alloc_collection_id,instance_index,machine_id,...,assigned_memory,page_cache_memory,sample_rate,cpu_usage_distribution,tail_cpu_usage_distribution,cluster,event,failed,cpus,memory
0,0,0,2,94591244395,3,1,200,0,144,168846390496,...,0.014435,0.000415,1.0,[0.00314331 0.00381088 0.00401306 0.00415039 0...,[0.00535583 0.00541687 0.00548553 0.00554657 0...,7,FAIL,1,0.020660,0.014435
1,1,2517305308183,2,260697606809,2,0,360,221495397286,335,85515092,...,0.000000,0.000000,1.0,[1.23977661e-05 1.23977661e-05 1.23977661e-05 ...,[1.23977661e-05 1.23977661e-05 1.23977661e-05 ...,7,FAIL,1,0.007240,0.001303
2,2,195684022913,6,276227177776,2,0,103,0,376,169321752432,...,0.010422,0.000235,1.0,[0.01344299 0.01809692 0.0201416 0.02246094 0...,[0.02902222 0.02929688 0.0295105 0.0296936 0...,7,SCHEDULE,0,0.048584,0.004166
3,3,0,2,10507389885,3,0,200,0,1977,178294817221,...,0.041626,0.000225,1.0,[0.03704834 0.04125977 0.04290771 0.04425049 0...,[0.05535889 0.05584717 0.05633545 0.05718994 0...,8,FAIL,1,0.070435,0.041626
4,4,1810627494172,3,25911621841,2,0,0,0,3907,231364893292,...,0.000272,0.000010,1.0,[0. 0. 0. 0. 0...,[0.00041485 0.00041485 0.00041485 0.00041485 0...,2,FINISH,0,0.002449,0.000232

In [15]:
constraint = df['constraint'].to_numpy()

In [16]:
count = 0
for i in constraint:
    if i == "[]":
        count += 1
print(count)

296152

In [17]:
df.drop(['constraint'],axis=1,inplace=True)
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 404161 entries, 0 to 405893
Data columns (total 32 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   Unnamed: 0                   404161 non-null  int64
 1   time                         404161 non-null  int64
 2   instance_events_type         404161 non-null  int64
 3   collection_id                404161 non-null  int64
 4   scheduling_class             404161 non-null  int64
 5   collection_type              404161 non-null  int64
 6   priority                     404161 non-null  int64
 7   alloc_collection_id          404161 non-null  int64
 8   instance_index               404161 non-null  int64
 9   machine_id                   404161 non-null  int64
 10  collections_events_type      404161 non-null  int64
 11  user                         404161 non-null  object
 12  collection_name              404161 non-null  object
 13  collection_logical_name      404161 non-null  object
 14  start_after_collection_ids   404161 non-null  object
 15  vertical_scaling             404161 non-null  float64
 16  scheduler                    404161 non-null  float64
 17  start_time                   404161 non-null  int64
 18  end_time                     404161 non-null  int64
 19  average_usage                404161 non-null  object
 20  maximum_usage                404161 non-null  object
 21  random_sample_usage          404161 non-null  object
 22  assigned_memory              404161 non-null  float64
 23  page_cache_memory            404161 non-null  float64
 24  sample_rate                  404161 non-null  float64
 25  cpu_usage_distribution       404161 non-null  object
 26  tail_cpu_usage_distribution  404161 non-null  object
 27  cluster                      404161 non-null  int64
 28  event                        404161 non-null  object
 29  failed                       404161 non-null  int64
 30  cpus                         404161 non-null  float64
 31  memory                       404161 non-null  float64
dtypes: float64(7), int64(15), object(10)
memory usage: 101.8+ MB

In [18]:
print(cpu_dist)

0         [0.00314331 0.00381088 0.00401306 0.00415039 0...
1         [1.23977661e-05 1.23977661e-05 1.23977661e-05 ...
2         [0.01344299 0.01809692 0.0201416  0.02246094 0...
3         [0.03704834 0.04125977 0.04290771 0.04425049 0...
4         [0.         0.         0.         0.         0...
                                ...
405889    [0.00022793 0.00822449 0.00866699 0.01246643 0...
405890    [0.01028442 0.02087402 0.02432251 0.02661133 0...
405891    [0.00857544 0.01472473 0.01660156 0.01873779 0...
405892    [0.00024414 0.00030136 0.00036907 0.00073719 0...
405893    [7.91549683e-05 9.59396362e-04 7.87353516e-03 ...
Name: cpu_usage_distribution, Length: 404161, dtype: object

In [19]:
import numpy as np
for idx,elem in enumerate(cpu_dist):
    elem = np.fromstring(elem.strip("[]"),sep=" ")
    cpu_dist[idx] = elem

In [20]:
for idx,elem in enumerate(cpu_tail):
    elem = np.fromstring(elem.strip("[]"),sep=" ")
    cpu_tail[idx] = elem

In [21]:
obj = df.select_dtypes(include=['object'])
obj.info()

<class 'pandas.core.frame.DataFrame'>
Index: 404161 entries, 0 to 405893
Data columns (total 10 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   user                         404161 non-null  object
 1   collection_name              404161 non-null  object
 2   collection_logical_name      404161 non-null  object
 3   start_after_collection_ids   404161 non-null  object
 4   average_usage                404161 non-null  object
 5   maximum_usage                404161 non-null  object
 6   random_sample_usage          404161 non-null  object
 7   cpu_usage_distribution       404161 non-null  object
 8   tail_cpu_usage_distribution  404161 non-null  object
 9   event                        404161 non-null  object
dtypes: object(10)
memory usage: 50.0+ MB