In [1]:
import pandas as pd

df = pd.read_csv('borg_traces_data.csv')

df.head()

,Unnamed: 0,time,instance_events_type,collection_id,scheduling_class,collection_type,priority,alloc_collection_id,instance_index,machine_id,...,assigned_memory,page_cache_memory,cycles_per_instruction,memory_accesses_per_instruction,sample_rate,cpu_usage_distribution,tail_cpu_usage_distribution,cluster,event,failed
0,0,0,2,94591244395,3,1,200,0,144,168846390496,...,0.014435,0.000415,NaN,NaN,1.0,[0.00314331 0.00381088 0.00401306 0.00415039 0...,[0.00535583 0.00541687 0.00548553 0.00554657 0...,7,FAIL,1
1,1,2517305308183,2,260697606809,2,0,360,221495397286,335,85515092,...,0.000000,0.000000,NaN,NaN,1.0,[1.23977661e-05 1.23977661e-05 1.23977661e-05 ...,[1.23977661e-05 1.23977661e-05 1.23977661e-05 ...,7,FAIL,1
2,2,195684022913,6,276227177776,2,0,103,0,376,169321752432,...,0.010422,0.000235,0.939919,0.001318,1.0,[0.01344299 0.01809692 0.0201416 0.02246094 0...,[0.02902222 0.02929688 0.0295105 0.0296936 0...,7,SCHEDULE,0
3,3,0,2,10507389885,3,0,200,0,1977,178294817221,...,0.041626,0.000225,1.359102,0.007643,1.0,[0.03704834 0.04125977 0.04290771 0.04425049 0...,[0.05535889 0.05584717 0.05633545 0.05718994 0...,8,FAIL,1
4,4,1810627494172,3,25911621841,2,0,0,0,3907,231364893292,...,0.000272,0.000010,NaN,NaN,1.0,[0. 0. 0. 0. 0...,[0.00041485 0.00041485 0.00041485 0.00041485 0...,2,FINISH,0

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 405894 entries, 0 to 405893
Data columns (total 34 columns):
 #   Column                           Non-Null Count   Dtype
---  ------                           --------------   -----
 0   Unnamed: 0                       405894 non-null  int64
 1   time                             405894 non-null  int64
 2   instance_events_type             405894 non-null  int64
 3   collection_id                    405894 non-null  int64
 4   scheduling_class                 405894 non-null  int64
 5   collection_type                  405894 non-null  int64
 6   priority                         405894 non-null  int64
 7   alloc_collection_id              405894 non-null  int64
 8   instance_index                   405894 non-null  int64
 9   machine_id                       405894 non-null  int64
 10  resource_request                 405120 non-null  object
 11  constraint                       405894 non-null  object
 12  collections_events_type          405894 non-null  int64
 13  user                             405894 non-null  object
 14  collection_name                  405894 non-null  object
 15  collection_logical_name          405894 non-null  object
 16  start_after_collection_ids       405894 non-null  object
 17  vertical_scaling                 404935 non-null  float64
 18  scheduler                        404935 non-null  float64
 19  start_time                       405894 non-null  int64
 20  end_time                         405894 non-null  int64
 21  average_usage                    405894 non-null  object
 22  maximum_usage                    405894 non-null  object
 23  random_sample_usage              405894 non-null  object
 24  assigned_memory                  405894 non-null  float64
 25  page_cache_memory                405894 non-null  float64
 26  cycles_per_instruction           281206 non-null  float64
 27  memory_accesses_per_instruction  281206 non-null  float64
 28  sample_rate                      405894 non-null  float64
 29  cpu_usage_distribution           405894 non-null  object
 30  tail_cpu_usage_distribution      405894 non-null  object
 31  cluster                          405894 non-null  int64
 32  event                            405894 non-null  object
 33  failed                           405894 non-null  int64
dtypes: float64(7), int64(15), object(12)
memory usage: 105.3+ MB

In [3]:
failed_events = ['FAIL','EVICT','LOST','KILL']
df.loc[df['event'].isin(failed_events),'failed'] = 1

df.head(20)

,Unnamed: 0,time,instance_events_type,collection_id,scheduling_class,collection_type,priority,alloc_collection_id,instance_index,machine_id,...,assigned_memory,page_cache_memory,cycles_per_instruction,memory_accesses_per_instruction,sample_rate,cpu_usage_distribution,tail_cpu_usage_distribution,cluster,event,failed
0,0,0,2,94591244395,3,1,200,0,144,168846390496,...,0.014435,4.148483e-04,NaN,NaN,1.000000,[0.00314331 0.00381088 0.00401306 0.00415039 0...,[0.00535583 0.00541687 0.00548553 0.00554657 0...,7,FAIL,1
1,1,2517305308183,2,260697606809,2,0,360,221495397286,335,85515092,...,0.000000,0.000000e+00,NaN,NaN,1.000000,[1.23977661e-05 1.23977661e-05 1.23977661e-05 ...,[1.23977661e-05 1.23977661e-05 1.23977661e-05 ...,7,FAIL,1
2,2,195684022913,6,276227177776,2,0,103,0,376,169321752432,...,0.010422,2.346039e-04,0.939919,0.001318,1.000000,[0.01344299 0.01809692 0.0201416 0.02246094 0...,[0.02902222 0.02929688 0.0295105 0.0296936 0...,7,SCHEDULE,0
3,3,0,2,10507389885,3,0,200,0,1977,178294817221,...,0.041626,2.250671e-04,1.359102,0.007643,1.000000,[0.03704834 0.04125977 0.04290771 0.04425049 0...,[0.05535889 0.05584717 0.05633545 0.05718994 0...,8,FAIL,1
4,4,1810627494172,3,25911621841,2,0,0,0,3907,231364893292,...,0.000272,9.536743e-06,NaN,NaN,1.000000,[0. 0. 0. 0. 0...,[0.00041485 0.00041485 0.00041485 0.00041485 0...,2,FINISH,0
5,5,1626744497194,6,235085571060,0,0,103,0,345,34202965855,...,0.005409,1.844406e-03,NaN,NaN,1.000000,[3.52859497e-05 1.76429749e-04 1.55067444e-03 ...,[0.13305664 0.1340332 0.13500977 0.13598633 0...,5,SCHEDULE,0
6,6,130721370174,0,275444626052,1,0,117,0,13138,10129440520,...,0.002190,5.722046e-06,0.646689,0.007937,1.000000,[0.00023937 0.00050068 0.00242233 0.00288773 0...,[0.00743866 0.00748444 0.00752258 0.00760651 0...,7,ENABLE,0
7,7,2373350421416,3,193223725812,2,0,103,0,393,447672988,...,0.001474,5.912781e-05,1.767994,0.017505,1.000000,[0.00054169 0.00374603 0.00450134 0.00513458 0...,[0.0098877 0.01011658 0.01023865 0.01055908 0...,7,FINISH,0
8,8,1970214287222,0,236368116431,0,0,0,0,19760,4236232523,...,0.006683,9.536743e-07,3.492855,0.009506,1.000000,[0.00013638 0.00014305 0.00015068 0.00015831 0...,[0.00028133 0.00029087 0.00029945 0.00030804 0...,5,ENABLE,0
9,9,2212203898561,6,296992962690,0,0,103,0,90,20826141104,...,0.006790,1.583099e-04,1.362406,0.012449,1.000000,[0.00172234 0.00854492 0.00947571 0.01029968 0...,[0.01663208 0.0173645 0.01773071 0.0184021 0...,7,SCHEDULE,0
10,10,36255576255,6,454520770906,0,1,116,0,1758,92336375,...,0.005013,5.407333e-04,NaN,NaN,1.000000,[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.],[0. 0. 0. 0. 0. 0. 0. 0. 0.],2,SCHEDULE,0
11,11,723622816016,1,346556401280,1,0,103,0,8880,19641579566,...,0.010422,2.861023e-06,0.998315,0.002872,1.000000,[0.00000000e+00 0.00000000e+00 0.00000000e+00 ...,[0.00190163 0.00190163 0.00190163 0.00190163 0...,6,EVICT,1
12,12,204389347359,3,39516992187,2,0,0,0,3658,374219354303,...,0.000232,0.000000e+00,1.417979,0.003366,1.000000,[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.],[0. 0. 0. 0. 0. 0. 0. 0. 0.],1,FINISH,0
13,13,1659671622423,5,784488673642,1,0,105,0,7776,13240065175,...,0.011017,7.629395e-06,3.684666,0.017217,1.000000,[0.00010395 0.00014496 0.00016403 0.00018024 0...,[0.00030327 0.00031376 0.00032997 0.00034714 0...,4,LOST,1
14,14,365676977693,5,784634965149,2,0,360,698302716873,641,50769016368,...,0.000000,1.974106e-04,NaN,NaN,1.000000,[0.00000000e+00 7.91549683e-05 2.02178955e-04 ...,[0.00654602 0.00656891 0.00658417 0.00659943 0...,4,LOST,1
15,15,1129358774407,5,330587204926,2,0,360,330587135936,882,104790909291,...,0.000000,2.109528e-03,0.830359,0.001282,1.000000,[0.00041485 0.02163696 0.02450562 0.02798462 0...,[0.04284668 0.04309082 0.043396 0.04370117 0...,1,LOST,1
16,16,0,2,27762125863,3,0,450,27762125764,37,32343383224,...,0.000000,1.916885e-04,2.249923,0.012976,0.996667,[0.01094055 0.01216125 0.01289368 0.01347351 0...,[0.02453613 0.0246582 0.02481079 0.0249939 0...,2,FAIL,1
17,17,1584163989226,0,288497456405,3,0,200,288497448483,1629,87028529945,...,0.000000,8.172989e-04,3.156894,0.016328,1.000000,[0.00024796 0.00026894 0.00027657 0.00028419 0...,[0.000597 0.00060463 0.00061226 0.00062084 0...,6,ENABLE,0
18,18,296066697739,1,784245858759,1,0,105,0,2198,5567221068,...,0.014969,1.983643e-04,NaN,NaN,1.000000,[0.00793457 0.00805664 0.00813293 0.00820923 0...,[0.00961304 0.00967407 0.00975037 0.00982666 0...,4,EVICT,1
19,19,116367066181,2,781395587588,2,0,360,698302736982,247,263475209,...,0.000000,1.131058e-03,1.098496,0.003790,1.000000,[0.00031757 0.00987244 0.01647949 0.01849365 0...,[0.07092285 0.07177734 0.07250977 0.07568359 0...,4,FAIL,1

In [12]:
null_idx = {}

for idx,val in enumerate(df.isnull().sum()):
    if val>0:
        null_idx[idx] = val

print(null_idx)
df.drop(df.columns[26:28],inplace=True,axis=1)
df.info()

{10: 774, 17: 959, 18: 959, 26: 124688, 27: 124688}
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 405894 entries, 0 to 405893
Data columns (total 32 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   Unnamed: 0                   405894 non-null  int64
 1   time                         405894 non-null  int64
 2   instance_events_type         405894 non-null  int64
 3   collection_id                405894 non-null  int64
 4   scheduling_class             405894 non-null  int64
 5   collection_type              405894 non-null  int64
 6   priority                     405894 non-null  int64
 7   alloc_collection_id          405894 non-null  int64
 8   instance_index               405894 non-null  int64
 9   machine_id                   405894 non-null  int64
 10  resource_request             405120 non-null  object
 11  constraint                   405894 non-null  object
 12  collections_events_type      405894 non-null  int64
 13  user                         405894 non-null  object
 14  collection_name              405894 non-null  object
 15  collection_logical_name      405894 non-null  object
 16  start_after_collection_ids   405894 non-null  object
 17  vertical_scaling             404935 non-null  float64
 18  scheduler                    404935 non-null  float64
 19  start_time                   405894 non-null  int64
 20  end_time                     405894 non-null  int64
 21  average_usage                405894 non-null  object
 22  maximum_usage                405894 non-null  object
 23  random_sample_usage          405894 non-null  object
 24  assigned_memory              405894 non-null  float64
 25  page_cache_memory            405894 non-null  float64
 26  sample_rate                  405894 non-null  float64
 27  cpu_usage_distribution       405894 non-null  object
 28  tail_cpu_usage_distribution  405894 non-null  object
 29  cluster                      405894 non-null  int64
 30  event                        405894 non-null  object
 31  failed                       405894 non-null  int64
dtypes: float64(5), int64(15), object(12)
memory usage: 99.1+ MB

In [13]:
df.drop(['Unnamed: 0','user','collection_name','collection_logical_name'],inplace=True,axis=1)

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 405894 entries, 0 to 405893
Data columns (total 28 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   time                         405894 non-null  int64
 1   instance_events_type         405894 non-null  int64
 2   collection_id                405894 non-null  int64
 3   scheduling_class             405894 non-null  int64
 4   collection_type              405894 non-null  int64
 5   priority                     405894 non-null  int64
 6   alloc_collection_id          405894 non-null  int64
 7   instance_index               405894 non-null  int64
 8   machine_id                   405894 non-null  int64
 9   resource_request             405120 non-null  object
 10  constraint                   405894 non-null  object
 11  collections_events_type      405894 non-null  int64
 12  start_after_collection_ids   405894 non-null  object
 13  vertical_scaling             404935 non-null  float64
 14  scheduler                    404935 non-null  float64
 15  start_time                   405894 non-null  int64
 16  end_time                     405894 non-null  int64
 17  average_usage                405894 non-null  object
 18  maximum_usage                405894 non-null  object
 19  random_sample_usage          405894 non-null  object
 20  assigned_memory              405894 non-null  float64
 21  page_cache_memory            405894 non-null  float64
 22  sample_rate                  405894 non-null  float64
 23  cpu_usage_distribution       405894 non-null  object
 24  tail_cpu_usage_distribution  405894 non-null  object
 25  cluster                      405894 non-null  int64
 26  event                        405894 non-null  object
 27  failed                       405894 non-null  int64
dtypes: float64(5), int64(14), object(9)
memory usage: 86.7+ MB

In [15]:
df.drop(['machine_id'],inplace=True,axis=1)

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 405894 entries, 0 to 405893
Data columns (total 27 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   time                         405894 non-null  int64
 1   instance_events_type         405894 non-null  int64
 2   collection_id                405894 non-null  int64
 3   scheduling_class             405894 non-null  int64
 4   collection_type              405894 non-null  int64
 5   priority                     405894 non-null  int64
 6   alloc_collection_id          405894 non-null  int64
 7   instance_index               405894 non-null  int64
 8   resource_request             405120 non-null  object
 9   constraint                   405894 non-null  object
 10  collections_events_type      405894 non-null  int64
 11  start_after_collection_ids   405894 non-null  object
 12  vertical_scaling             404935 non-null  float64
 13  scheduler                    404935 non-null  float64
 14  start_time                   405894 non-null  int64
 15  end_time                     405894 non-null  int64
 16  average_usage                405894 non-null  object
 17  maximum_usage                405894 non-null  object
 18  random_sample_usage          405894 non-null  object
 19  assigned_memory              405894 non-null  float64
 20  page_cache_memory            405894 non-null  float64
 21  sample_rate                  405894 non-null  float64
 22  cpu_usage_distribution       405894 non-null  object
 23  tail_cpu_usage_distribution  405894 non-null  object
 24  cluster                      405894 non-null  int64
 25  event                        405894 non-null  object
 26  failed                       405894 non-null  int64
dtypes: float64(5), int64(13), object(9)
memory usage: 83.6+ MB

In [23]:
resources = df[df.columns[8]].dropna()

cpus = []
memory = []

In [25]:
import ast

for resource in resources:
    resource = ast.literal_eval(resource)
    cpus.append(resource['cpus'])
    memory.append(resource['memory'])

In [26]:
print(resources[0])

{'cpus': 0.020660400390625, 'memory': 0.014434814453125}

In [27]:
fill_na = {'cpus':sum(cpus)/len(cpus),'memory':sum(memory)/len(memory)}
print(fill_na)

{'cpus': 0.015336473417978905, 'memory': 0.009041759748406132}

In [31]:
df.loc[df['resource_request'].isnull(),'resource_request'] = fill_na

In [42]:
null_idx = df[df['resource_request'].isnull()].index.tolist()
df.loc[null_idx,'resource_request'] = str(fill_na)

In [54]:
import math
scaling = df['vertical_scaling'].dropna().tolist()

avg_scaling = sum(scaling)/len(scaling)
print(set(scaling))
avg_scaling = math.ceil(avg_scaling)

{1.0, 2.0, 3.0}

In [55]:
df.loc[df['vertical_scaling'].isna(),'vertical_scaling'] = avg_scaling

df.isnull().sum()

time                             0
instance_events_type             0
collection_id                    0
scheduling_class                 0
collection_type                  0
priority                         0
alloc_collection_id              0
instance_index                   0
resource_request                 0
constraint                       0
collections_events_type          0
start_after_collection_ids       0
vertical_scaling                 0
scheduler                      959
start_time                       0
end_time                         0
average_usage                    0
maximum_usage                    0
random_sample_usage              0
assigned_memory                  0
page_cache_memory                0
sample_rate                      0
cpu_usage_distribution           0
tail_cpu_usage_distribution      0
cluster                          0
event                            0
failed                           0
dtype: int64

In [62]:
scheduler = df['scheduler'].dropna().tolist()
avg_scheduler = sum(scheduler)/len(scheduler)
print(avg_scheduler)
avg_scheduler = 0

df.loc[df['scheduler'].isna(),'scheduler'] = avg_scheduler
df.isnull().sum()

0.3704224134737674

time                           0
instance_events_type           0
collection_id                  0
scheduling_class               0
collection_type                0
priority                       0
alloc_collection_id            0
instance_index                 0
resource_request               0
constraint                     0
collections_events_type        0
start_after_collection_ids     0
vertical_scaling               0
scheduler                      0
start_time                     0
end_time                       0
average_usage                  0
maximum_usage                  0
random_sample_usage            0
assigned_memory                0
page_cache_memory              0
sample_rate                    0
cpu_usage_distribution         0
tail_cpu_usage_distribution    0
cluster                        0
event                          0
failed                         0
dtype: int64

In [63]:
df.drop(['cluster','event','tail_cpu_usage_distribution','cpu_usage_distribution'],inplace=True,axis=1)

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 405894 entries, 0 to 405893
Data columns (total 23 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   time                        405894 non-null  int64
 1   instance_events_type        405894 non-null  int64
 2   collection_id               405894 non-null  int64
 3   scheduling_class            405894 non-null  int64
 4   collection_type             405894 non-null  int64
 5   priority                    405894 non-null  int64
 6   alloc_collection_id         405894 non-null  int64
 7   instance_index              405894 non-null  int64
 8   resource_request            405894 non-null  object
 9   constraint                  405894 non-null  object
 10  collections_events_type     405894 non-null  int64
 11  start_after_collection_ids  405894 non-null  object
 12  vertical_scaling            405894 non-null  float64
 13  scheduler                   405894 non-null  float64
 14  start_time                  405894 non-null  int64
 15  end_time                    405894 non-null  int64
 16  average_usage               405894 non-null  object
 17  maximum_usage               405894 non-null  object
 18  random_sample_usage         405894 non-null  object
 19  assigned_memory             405894 non-null  float64
 20  page_cache_memory           405894 non-null  float64
 21  sample_rate                 405894 non-null  float64
 22  failed                      405894 non-null  int64
dtypes: float64(5), int64(12), object(6)
memory usage: 71.2+ MB

In [72]:
obj_idx = df.select_dtypes(include=['object']).columns.tolist()

clean = df.drop(obj_idx,axis=1)
clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 405894 entries, 0 to 405893
Data columns (total 17 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   time                     405894 non-null  int64
 1   instance_events_type     405894 non-null  int64
 2   collection_id            405894 non-null  int64
 3   scheduling_class         405894 non-null  int64
 4   collection_type          405894 non-null  int64
 5   priority                 405894 non-null  int64
 6   alloc_collection_id      405894 non-null  int64
 7   instance_index           405894 non-null  int64
 8   collections_events_type  405894 non-null  int64
 9   vertical_scaling         405894 non-null  float64
 10  scheduler                405894 non-null  float64
 11  start_time               405894 non-null  int64
 12  end_time                 405894 non-null  int64
 13  assigned_memory          405894 non-null  float64
 14  page_cache_memory        405894 non-null  float64
 15  sample_rate              405894 non-null  float64
 16  failed                   405894 non-null  int64
dtypes: float64(5), int64(12)
memory usage: 52.6 MB

In [73]:
exec_time = df['end_time'] - df['start_time']

In [ ]:
df.drop(['start_time','end_time'],inplace=True,axis=1)
df['exec_time'] = exec_time
df.head()

In [77]:
df.drop(['constraint','random_sample_usage'],inplace=True,axis=1)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 405894 entries, 0 to 405893
Data columns (total 20 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   time                        405894 non-null  int64
 1   instance_events_type        405894 non-null  int64
 2   collection_id               405894 non-null  int64
 3   scheduling_class            405894 non-null  int64
 4   collection_type             405894 non-null  int64
 5   priority                    405894 non-null  int64
 6   alloc_collection_id         405894 non-null  int64
 7   instance_index              405894 non-null  int64
 8   resource_request            405894 non-null  object
 9   collections_events_type     405894 non-null  int64
 10  start_after_collection_ids  405894 non-null  object
 11  vertical_scaling            405894 non-null  float64
 12  scheduler                   405894 non-null  float64
 13  average_usage               405894 non-null  object
 14  maximum_usage               405894 non-null  object
 15  assigned_memory             405894 non-null  float64
 16  page_cache_memory           405894 non-null  float64
 17  sample_rate                 405894 non-null  float64
 18  failed                      405894 non-null  int64
 19  exec_time                   405894 non-null  int64
dtypes: float64(5), int64(11), object(4)
memory usage: 61.9+ MB

In [78]:
resources = df['resource_request'].tolist()
cpus.clear()
memory.clear()

for resource in resources:
    resource = ast.literal_eval(resource)

    cpus.append(resource['cpus'])
    memory.append(resource['memory'])

df.drop(['resource_request'],inplace=True,axis=1)

In [79]:
df['req_cpus'] = cpus
df['req_memory'] = memory

df.head()

,time,instance_events_type,collection_id,scheduling_class,collection_type,priority,alloc_collection_id,instance_index,collections_events_type,start_after_collection_ids,...,scheduler,average_usage,maximum_usage,assigned_memory,page_cache_memory,sample_rate,failed,exec_time,req_cpus,req_memory
0,0,2,94591244395,3,1,200,0,144,2,[],...,0.0,"{'cpus': 0.00466156005859375, 'memory': 0.0059...","{'cpus': 0.01190185546875, 'memory': 0.0059356...",0.014435,0.000415,1.0,1,300000000,0.020660,0.014435
1,2517305308183,2,260697606809,2,0,360,221495397286,335,2,[],...,0.0,"{'cpus': 0.0, 'memory': 9.5367431640625e-07}","{'cpus': 0.0, 'memory': 9.5367431640625e-07}",0.000000,0.000000,1.0,1,1000000,0.007240,0.001303
2,195684022913,6,276227177776,2,0,103,0,376,6,[],...,1.0,"{'cpus': 0.024200439453125, 'memory': 0.002788...","{'cpus': 0.06005859375, 'memory': 0.0028457641...",0.010422,0.000235,1.0,0,300000000,0.048584,0.004166
3,0,2,10507389885,3,0,200,0,1977,2,[],...,0.0,"{'cpus': 0.047607421875, 'memory': 0.034423828...","{'cpus': 0.13330078125, 'memory': 0.03466796875}",0.041626,0.000225,1.0,1,300000000,0.070435,0.041626
4,1810627494172,3,25911621841,2,0,0,0,3907,3,[],...,0.0,"{'cpus': 0.000270843505859375, 'memory': 7.629...","{'cpus': 0.00041484832763671875, 'memory': 7.6...",0.000272,0.000010,1.0,0,2000000,0.002449,0.000232

In [83]:
cpus.clear()
memory.clear()
usage = df['average_usage'].tolist()

for resource in usage:
    resource = ast.literal_eval(resource)

    cpus.append(resource['cpus'])
    memory.append(resource['memory'])
df.drop(['average_usage'],axis=1,inplace=True)
df['avg_cpus'] = cpus
df['avg_memory'] = memory

In [ ]:
cpus.clear()
memory.clear()
usage = df['maximum_usage'].tolist()
null_idx.clear()

for idx,resource in enumerate(usage):
    resource = ast.literal_eval(resource)
    if not resource:
        null_idx.append(idx)
        continue
    
    cpus.append(resource['cpus'])
    memory.append(resource['memory'])

In [90]:
df.drop(['maximum_usage'],inplace=True,axis=1)

In [91]:
df['max_cpus'] = cpus
df['max_memory'] = memory

In [92]:
df.head()

,time,instance_events_type,collection_id,scheduling_class,collection_type,priority,alloc_collection_id,instance_index,collections_events_type,start_after_collection_ids,...,page_cache_memory,sample_rate,failed,exec_time,req_cpus,req_memory,avg_cpus,avg_memory,max_cpus,max_memory
0,0,2,94591244395,3,1,200,0,144,2,[],...,0.000415,1.0,1,300000000,0.020660,0.014435,0.004662,5.920410e-03,0.011902,5.935669e-03
1,2517305308183,2,260697606809,2,0,360,221495397286,335,2,[],...,0.000000,1.0,1,1000000,0.007240,0.001303,0.000000,9.536743e-07,0.000000,9.536743e-07
2,195684022913,6,276227177776,2,0,103,0,376,6,[],...,0.000235,1.0,0,300000000,0.048584,0.004166,0.024200,2.788544e-03,0.060059,2.845764e-03
3,0,2,10507389885,3,0,200,0,1977,2,[],...,0.000225,1.0,1,300000000,0.070435,0.041626,0.047607,3.442383e-02,0.133301,3.466797e-02
4,1810627494172,3,25911621841,2,0,0,0,3907,3,[],...,0.000010,1.0,0,2000000,0.002449,0.000232,0.000271,7.629395e-05,0.000415,7.629395e-05

In [93]:
df.drop(['start_after_collection_ids'],inplace=True,axis=1)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 405894 entries, 0 to 405893
Data columns (total 22 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   time                     405894 non-null  int64
 1   instance_events_type     405894 non-null  int64
 2   collection_id            405894 non-null  int64
 3   scheduling_class         405894 non-null  int64
 4   collection_type          405894 non-null  int64
 5   priority                 405894 non-null  int64
 6   alloc_collection_id      405894 non-null  int64
 7   instance_index           405894 non-null  int64
 8   collections_events_type  405894 non-null  int64
 9   vertical_scaling         405894 non-null  float64
 10  scheduler                405894 non-null  float64
 11  assigned_memory          405894 non-null  float64
 12  page_cache_memory        405894 non-null  float64
 13  sample_rate              405894 non-null  float64
 14  failed                   405894 non-null  int64
 15  exec_time                405894 non-null  int64
 16  req_cpus                 405894 non-null  float64
 17  req_memory               405894 non-null  float64
 18  avg_cpus                 405894 non-null  float64
 19  avg_memory               405894 non-null  float64
 20  max_cpus                 405894 non-null  float64
 21  max_memory               400967 non-null  float64
dtypes: float64(11), int64(11)
memory usage: 68.1 MB

In [95]:
df.drop(['collections_events_type'],inplace=True,axis=1)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 405894 entries, 0 to 405893
Data columns (total 21 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   time                  405894 non-null  int64
 1   instance_events_type  405894 non-null  int64
 2   collection_id         405894 non-null  int64
 3   scheduling_class      405894 non-null  int64
 4   collection_type       405894 non-null  int64
 5   priority              405894 non-null  int64
 6   alloc_collection_id   405894 non-null  int64
 7   instance_index        405894 non-null  int64
 8   vertical_scaling      405894 non-null  float64
 9   scheduler             405894 non-null  float64
 10  assigned_memory       405894 non-null  float64
 11  page_cache_memory     405894 non-null  float64
 12  sample_rate           405894 non-null  float64
 13  failed                405894 non-null  int64
 14  exec_time             405894 non-null  int64
 15  req_cpus              405894 non-null  float64
 16  req_memory            405894 non-null  float64
 17  avg_cpus              405894 non-null  float64
 18  avg_memory            405894 non-null  float64
 19  max_cpus              405894 non-null  float64
 20  max_memory            400967 non-null  float64
dtypes: float64(11), int64(10)
memory usage: 65.0 MB

In [96]:
df.to_csv('regression_data.csv')