In [1]:
import pandas as pd

df = pd.read_csv('borg_traces_data.csv')

df.head()

,Unnamed: 0,time,instance_events_type,collection_id,scheduling_class,collection_type,priority,alloc_collection_id,instance_index,machine_id,...,assigned_memory,page_cache_memory,cycles_per_instruction,memory_accesses_per_instruction,sample_rate,cpu_usage_distribution,tail_cpu_usage_distribution,cluster,event,failed
0,0,0,2,94591244395,3,1,200,0,144,168846390496,...,0.014435,0.000415,NaN,NaN,1.0,[0.00314331 0.00381088 0.00401306 0.00415039 0...,[0.00535583 0.00541687 0.00548553 0.00554657 0...,7,FAIL,1
1,1,2517305308183,2,260697606809,2,0,360,221495397286,335,85515092,...,0.000000,0.000000,NaN,NaN,1.0,[1.23977661e-05 1.23977661e-05 1.23977661e-05 ...,[1.23977661e-05 1.23977661e-05 1.23977661e-05 ...,7,FAIL,1
2,2,195684022913,6,276227177776,2,0,103,0,376,169321752432,...,0.010422,0.000235,0.939919,0.001318,1.0,[0.01344299 0.01809692 0.0201416 0.02246094 0...,[0.02902222 0.02929688 0.0295105 0.0296936 0...,7,SCHEDULE,0
3,3,0,2,10507389885,3,0,200,0,1977,178294817221,...,0.041626,0.000225,1.359102,0.007643,1.0,[0.03704834 0.04125977 0.04290771 0.04425049 0...,[0.05535889 0.05584717 0.05633545 0.05718994 0...,8,FAIL,1
4,4,1810627494172,3,25911621841,2,0,0,0,3907,231364893292,...,0.000272,0.000010,NaN,NaN,1.0,[0. 0. 0. 0. 0...,[0.00041485 0.00041485 0.00041485 0.00041485 0...,2,FINISH,0

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 405894 entries, 0 to 405893
Data columns (total 34 columns):
 #   Column                           Non-Null Count   Dtype
---  ------                           --------------   -----
 0   Unnamed: 0                       405894 non-null  int64
 1   time                             405894 non-null  int64
 2   instance_events_type             405894 non-null  int64
 3   collection_id                    405894 non-null  int64
 4   scheduling_class                 405894 non-null  int64
 5   collection_type                  405894 non-null  int64
 6   priority                         405894 non-null  int64
 7   alloc_collection_id              405894 non-null  int64
 8   instance_index                   405894 non-null  int64
 9   machine_id                       405894 non-null  int64
 10  resource_request                 405120 non-null  object
 11  constraint                       405894 non-null  object
 12  collections_events_type          405894 non-null  int64
 13  user                             405894 non-null  object
 14  collection_name                  405894 non-null  object
 15  collection_logical_name          405894 non-null  object
 16  start_after_collection_ids       405894 non-null  object
 17  vertical_scaling                 404935 non-null  float64
 18  scheduler                        404935 non-null  float64
 19  start_time                       405894 non-null  int64
 20  end_time                         405894 non-null  int64
 21  average_usage                    405894 non-null  object
 22  maximum_usage                    405894 non-null  object
 23  random_sample_usage              405894 non-null  object
 24  assigned_memory                  405894 non-null  float64
 25  page_cache_memory                405894 non-null  float64
 26  cycles_per_instruction           281206 non-null  float64
 27  memory_accesses_per_instruction  281206 non-null  float64
 28  sample_rate                      405894 non-null  float64
 29  cpu_usage_distribution           405894 non-null  object
 30  tail_cpu_usage_distribution      405894 non-null  object
 31  cluster                          405894 non-null  int64
 32  event                            405894 non-null  object
 33  failed                           405894 non-null  int64
dtypes: float64(7), int64(15), object(12)
memory usage: 105.3+ MB